// ---------------------------------------------------------------------------
// GENERATED by scripts/generate-academy-manifest.mjs — do not edit by hand.
//
// This Academy's answer to the platform's content contract. The school reads
// slots (src/content/academyContent.js); this file says what this Academy puts
// in each one. Re-run the generator after adding or removing a content file.
//
// A slot this Academy has nothing for is simply absent. Blank is expected.
// ---------------------------------------------------------------------------

import { activeMilestone, hasMilestones, leadStatus, milestoneProgress, milestonesFor, startByFor } from './data/academicSuccessCenter/assignmentMilestones.js';
import { EXCLUDED_RANGES, assignmentCandidatesForSlot, availableDueDates, nextAssignmentRecommendation, resolveSuggestedDueDate } from './data/academicSuccessCenter/assignmentRecommendations.js';
import { BLACK_EXCELLENCE_KNOWN_GAPS, blackAmericanAuthorsForSubject, blackExcellenceBooksForSubject } from './data/academicSuccessCenter/blackExcellenceLibrary.js';
import { BOOK_RANGE_LABELS, bookRationale, rationaleFor } from './data/academicSuccessCenter/bookRationale.js';
import { bookRecommendations, candidatesForBook, nextRecommendationForBook } from './data/academicSuccessCenter/bookRecommendations.js';
import { ACADEMIC_ASSIGNMENT_TYPES, ACADEMIC_BOOK_TYPES, ACADEMIC_SUBJECT_ORDER, ACADEMIC_SUCCESS_CENTER_QUARTER_ORDER, quarterlyAcademicPlaceholders, subjectBookPlaceholders } from './data/academicSuccessCenter/placeholders.js';
import { RUBRIC_LEVELS, criteriaForFormat, findFormat, formatsForType, reflectionPromptFor, sizeFor, suggestedGradeFromRubric } from './data/academicSuccessCenter/reportFormats.js';
import { GEORGIA_DAYS_REQUIRED, GEORGIA_LAW_CITATION, GEORGIA_MINUTES_PER_DAY, GEORGIA_REQUIRED_SUBJECTS, GEORGIA_REQUIREMENTS, declarationCoversToday, instructionProgress, nextDeclarationDeadline, stateName } from './data/admin/georgiaCompliance.js';
import { MISSION_QUARTERS, MISSION_RUBRIC_CRITERIA, MISSION_STATUS_LABELS, draftMissionFeedback, findProposal, missionGrowth, missionScoreTotals, proposalsForQuarter } from './data/admin/missionEvaluations.js';
import { gardenBriefs, getGardenBriefById } from './data/gardening/gardenBriefs.js';
import { buildsUnlockedBy, gardenBuildTrack, gardenCapstone } from './data/gardening/gardenBuildTrack.js';
import { GARDEN_Q1_END, GARDEN_Q1_START, GARDEN_Q2_END, GARDEN_Q2_START, GARDEN_Q3_END, GARDEN_Q3_START, GARDEN_Q4_END, GARDEN_Q4_START, GARDEN_SUMMER_END, GARDEN_SUMMER_START, gardenCalendar, getGardenDayForDate, getGardenDayForWeekOf, getNextGardenDay, getScheduledBriefDays, isClosedGardenDay } from './data/gardening/gardenCalendar.js';
import { gardenProjects } from './data/gardening/gardenProjects.js';
import { GUITAR_DAILY_MINUTES, GUITAR_SESSION_SHAPE, getCurrentGuitarSkill, getGuitarSkillByNumber, guitarLadderProgress, guitarSkillLadder } from './data/guitar/guitarSkillLadder.js';
import { GUITAR_OWN_SLOTS, guitarOwnSongGuidance, guitarPerformanceMoment, guitarStarterSongs } from './data/guitar/guitarSongs.js';
import { GUITAR_THEORY_QUARTER, getGuitarTheoryItem, guitarTheory } from './data/guitar/guitarTheory.js';
import { GUITAR_LINKS_VERIFIED_ON, getGuitarTool, guitarEducators, guitarFeedbackPlaces, guitarTools } from './data/guitar/guitarTools.js';
import { DEFAULT_FIELD_TRIPS, LIBRARY_TRIP_RENAMES } from './data/fieldTrips/fieldTripSeed.js';
import { EXTERNAL_GAMES_LIBRARY } from './data/games/externalGamesLibrary.js';
import { LAUNCH_SCORE_LABELS, PROPELLANT_OPTIONS, STAGING_OPTIONS, TRAJECTORY_EVENT, WEIGHT_BUDGET_CATEGORIES, WEIGHT_BUDGET_TOTAL_POINTS } from './data/games/launchDirectorContent.js';
import { BUDGET_CATEGORIES, BUDGET_TOTAL_POINTS, ECONOMIC_SYSTEMS, GOVERNMENT_TYPES, NATION_SCORE_LABELS, TRADE_EVENT } from './data/games/nationCommandContent.js';
import { QUIZ_PLATFORMS, QUIZ_PLATFORM_IDS } from './data/games/quizPlatforms.js';
import { DAILY_LINE_COUNT, NOVA_LINES, QUOTED, getDailyLine } from './data/mentor/dailyLines.js';
import { KHAN_FIRST_SEED, KHAN_RETITLES, KHAN_SEED_BATCHES, KHAN_URL_FIXES } from './data/khanSeed/khanSeedBatches.js';
import { GRAMMAR_COURSES, KHAN_GRAMMAR_UNITS, LEGACY_GRAMMAR_TITLES, generalGrammarUnitByUrl, grammarRowTitle, grammarUnitUrl, khanGrammarUnitByUrl, khanGrammarUnitForUrl } from './data/khan/grammarCourseOrder.js';
import { SCIENCE_CANONICAL_KEYS, SCIENCE_CANONICAL_TITLES, SCIENCE_COURSES, SCIENCE_COURSE_CHALLENGES, scienceCanonicalRow, scienceCourseChallengeRows, scienceCourseForUrl, scienceCoverageByCourse, scienceRowsFor } from './data/khan/scienceSequence.js';
import { allLessons } from './data/lessons/index.js';
import { ASSIGNMENT_CORRECTIONS, ASSIGNMENT_RETITLES, BOOK_SWAPS, RETIRED_ASSIGNMENT_SLOTS } from './data/migrations/assignmentMigrations.js';
import { navGroups, navParentTab, navSchoolName, navSchoolTagline } from './data/nav/nav.js';
import { EXERCISE_DEMO_VIDEOS } from './data/pe/exerciseDemoVideos.js';
import { CATEGORY_LABELS, exerciseLibrary } from './data/pe/exerciseLibrary.js';
import { nutritionChallenges, nutritionTopics, recipeLibrary, shoppingListCategories } from './data/pe/nutritionContent.js';
import { WEEKLY_PLAN, WORKOUT_NOTES } from './data/pe/weeklyWorkoutPlan.js';
import { templates } from './data/practice/problemTemplates.js';
import { aerospaceProjects } from './data/aerospace/aerospaceProjects.js';
import { roboticsProjects } from './data/robotics/roboticsProjects.js';
import { scienceExperiments } from './data/science/scienceExperiments.js';
import { technologyProjects } from './data/technology/technologyProjects.js';
import { HQ_CREW } from './data/hqCrew.js';
import { LESSON_PRINTOUTS, PRINTOUT_KINDS, SUBJECT_JOURNALS } from './data/printouts.js';
import { AVATAR_GEAR, COIN_CATALOG, COSMETIC_REPRICE, DREAM_ICON, DREAM_REWARDS, DREAM_TIER, HQ_ITEMS, MISSION_EQUIPMENT, REAL_WORLD_REWARDS, SEEDED_REWARD_LADDER_MAP, TIERS_REQUIRING_PARENT } from './data/rewardCatalog.js';
import { ACTIVE_SUBJECTS, KHAN_TAUGHT_SUBJECTS, LESSON_TRACK_SUBJECTS, PARTICIPATION_SUBJECTS, STRANDS, SUBJECT_ALIASES, SUBJECT_CARD_LABELS, SUBJECT_LABELS } from './subjects.js';
import { defaultSchedule } from './data/schedule/defaultSchedule.js';
import { SCHOOL_HOLIDAYS } from './data/schedule/schoolHolidays.js';
import { HOLIDAY_NOTE, WEEK_PATTERN } from './data/schedule/weekPattern.js';
import { dailyDrills } from './data/writing/dailyDrills.js';
import { DRILL_REQUIREMENTS } from './data/writing/drillRequirements.js';
import { PROMPT_LESSONS } from './data/writing/promptLessons.js';
import { spellingWordPool } from './data/writing/spellingWordPool.js';
import { EDCLUB_PORTAL_URL, ERGONOMICS_CHECKLIST, typingLessons } from './data/writing/typingLessons.js';
import { vocabularyWordPool } from './data/writing/vocabularyWordPool.js';
import { SCHOOL_YEAR_START, weeklyWritingSchedule } from './data/writing/weeklySchedule.js';
import { writingPrompts } from './data/writing/writingPrompts.js';

export const academicCenter = { ACADEMIC_ASSIGNMENT_TYPES, ACADEMIC_BOOK_TYPES, ACADEMIC_SUBJECT_ORDER, ACADEMIC_SUCCESS_CENTER_QUARTER_ORDER, BLACK_EXCELLENCE_KNOWN_GAPS, BOOK_RANGE_LABELS, EXCLUDED_RANGES, RUBRIC_LEVELS, activeMilestone, assignmentCandidatesForSlot, availableDueDates, blackAmericanAuthorsForSubject, blackExcellenceBooksForSubject, bookRationale, bookRecommendations, candidatesForBook, criteriaForFormat, findFormat, formatsForType, hasMilestones, leadStatus, milestoneProgress, milestonesFor, nextAssignmentRecommendation, nextRecommendationForBook, quarterlyAcademicPlaceholders, rationaleFor, reflectionPromptFor, resolveSuggestedDueDate, sizeFor, startByFor, subjectBookPlaceholders, suggestedGradeFromRubric };

export const compliance = { GEORGIA_DAYS_REQUIRED, GEORGIA_LAW_CITATION, GEORGIA_MINUTES_PER_DAY, GEORGIA_REQUIRED_SUBJECTS, GEORGIA_REQUIREMENTS, MISSION_QUARTERS, MISSION_RUBRIC_CRITERIA, MISSION_STATUS_LABELS, declarationCoversToday, draftMissionFeedback, findProposal, instructionProgress, missionGrowth, missionScoreTotals, nextDeclarationDeadline, proposalsForQuarter, stateName };

export const electives = { GARDEN_Q1_END, GARDEN_Q1_START, GARDEN_Q2_END, GARDEN_Q2_START, GARDEN_Q3_END, GARDEN_Q3_START, GARDEN_Q4_END, GARDEN_Q4_START, GARDEN_SUMMER_END, GARDEN_SUMMER_START, GUITAR_DAILY_MINUTES, GUITAR_LINKS_VERIFIED_ON, GUITAR_OWN_SLOTS, GUITAR_SESSION_SHAPE, GUITAR_THEORY_QUARTER, buildsUnlockedBy, gardenBriefs, gardenBuildTrack, gardenCalendar, gardenCapstone, gardenProjects, getCurrentGuitarSkill, getGardenBriefById, getGardenDayForDate, getGardenDayForWeekOf, getGuitarSkillByNumber, getGuitarTheoryItem, getGuitarTool, getNextGardenDay, getScheduledBriefDays, guitarEducators, guitarFeedbackPlaces, guitarLadderProgress, guitarOwnSongGuidance, guitarPerformanceMoment, guitarSkillLadder, guitarStarterSongs, guitarTheory, guitarTools, isClosedGardenDay };

export const fieldTrips = { DEFAULT_FIELD_TRIPS, LIBRARY_TRIP_RENAMES };

export const games = { BUDGET_CATEGORIES, BUDGET_TOTAL_POINTS, ECONOMIC_SYSTEMS, EXTERNAL_GAMES_LIBRARY, GOVERNMENT_TYPES, LAUNCH_SCORE_LABELS, NATION_SCORE_LABELS, PROPELLANT_OPTIONS, QUIZ_PLATFORMS, QUIZ_PLATFORM_IDS, STAGING_OPTIONS, TRADE_EVENT, TRAJECTORY_EVENT, WEIGHT_BUDGET_CATEGORIES, WEIGHT_BUDGET_TOTAL_POINTS };

export const guide = { DAILY_LINE_COUNT, NOVA_LINES, QUOTED, getDailyLine };

export const khanSeed = { KHAN_FIRST_SEED, KHAN_RETITLES, KHAN_SEED_BATCHES, KHAN_URL_FIXES };

export const khanSequences = { GRAMMAR_COURSES, KHAN_GRAMMAR_UNITS, LEGACY_GRAMMAR_TITLES, SCIENCE_CANONICAL_KEYS, SCIENCE_CANONICAL_TITLES, SCIENCE_COURSES, SCIENCE_COURSE_CHALLENGES, generalGrammarUnitByUrl, grammarRowTitle, grammarUnitUrl, khanGrammarUnitByUrl, khanGrammarUnitForUrl, scienceCanonicalRow, scienceCourseChallengeRows, scienceCourseForUrl, scienceCoverageByCourse, scienceRowsFor };

export const lessons = { allLessons };

export const migrations = { ASSIGNMENT_CORRECTIONS, ASSIGNMENT_RETITLES, BOOK_SWAPS, RETIRED_ASSIGNMENT_SLOTS };

export const nav = { navGroups, navParentTab, navSchoolName, navSchoolTagline };

export const pe = { CATEGORY_LABELS, EXERCISE_DEMO_VIDEOS, WEEKLY_PLAN, WORKOUT_NOTES, exerciseLibrary, nutritionChallenges, nutritionTopics, recipeLibrary, shoppingListCategories };

export const practice = { templates };

export const projects = { aerospaceProjects, roboticsProjects, scienceExperiments, technologyProjects };

export const rewards = { AVATAR_GEAR, COIN_CATALOG, COSMETIC_REPRICE, DREAM_ICON, DREAM_REWARDS, DREAM_TIER, HQ_CREW, HQ_ITEMS, LESSON_PRINTOUTS, MISSION_EQUIPMENT, PRINTOUT_KINDS, REAL_WORLD_REWARDS, SEEDED_REWARD_LADDER_MAP, SUBJECT_JOURNALS, TIERS_REQUIRING_PARENT };

export const subjects = { ACTIVE_SUBJECTS, KHAN_TAUGHT_SUBJECTS, LESSON_TRACK_SUBJECTS, PARTICIPATION_SUBJECTS, STRANDS, SUBJECT_ALIASES, SUBJECT_CARD_LABELS, SUBJECT_LABELS };

export const timetable = { HOLIDAY_NOTE, SCHOOL_HOLIDAYS, WEEK_PATTERN, defaultSchedule };

export const writing = { DRILL_REQUIREMENTS, EDCLUB_PORTAL_URL, ERGONOMICS_CHECKLIST, PROMPT_LESSONS, SCHOOL_YEAR_START, dailyDrills, spellingWordPool, typingLessons, vocabularyWordPool, weeklyWritingSchedule, writingPrompts };

/**
 * This Academy's palette and print rules.
 *
 * The theme slot answers one question: what does this school look like?
 *
 * A loader rather than a static import so the stylesheet travels in this
 * Academy's chunk and loads when this Academy does. A static import here
 * would put every Academy's theme in every learner's download, which is the
 * thing the folder split exists to prevent.
 */
export const theme = { appearance: () => import('./academy.css') };

// This school's own screens: tab id -> how to load it. Hand-written in
// views.js, which this generated file only re-exports — see that file and
// src/content/slots/views.js.
export { views } from './views.js';
