// ---------------------------------------------------------------------------
// GENERATED by scripts/generate-academy-manifest.mjs — do not edit by hand.
//
// This Academy's answer to the platform's content contract. The school reads
// slots (src/content/academyContent.js); this file says what this Academy puts
// in each one. Re-run the generator after adding or removing a content file.
//
// A slot this Academy has nothing for is simply absent. Blank is expected.
// ---------------------------------------------------------------------------

import { activeMilestone, hasMilestones, leadStatus, milestoneProgress, milestonesFor, startByFor } from './data/academicSuccessCenter/assignmentMilestones.js';
import { EXCLUDED_RANGES, assignmentCandidatesForSlot, availableDueDates, nextAssignmentRecommendation, resolveSuggestedDueDate } from './data/academicSuccessCenter/assignmentRecommendations.js';
import { BLACK_EXCELLENCE_KNOWN_GAPS, blackAmericanAuthorsForSubject, blackExcellenceBooksForSubject } from './data/academicSuccessCenter/blackExcellenceLibrary.js';
import { BOOK_RANGE_LABELS, bookRationale, rationaleFor } from './data/academicSuccessCenter/bookRationale.js';
import { bookRecommendations, candidatesForBook, nextRecommendationForBook } from './data/academicSuccessCenter/bookRecommendations.js';
import { ACADEMIC_ASSIGNMENT_TYPES, ACADEMIC_BOOK_TYPES, ACADEMIC_SUBJECT_ORDER, ACADEMIC_SUCCESS_CENTER_QUARTER_ORDER, quarterlyAcademicPlaceholders, subjectBookPlaceholders } from './data/academicSuccessCenter/placeholders.js';
import { RUBRIC_LEVELS, criteriaForFormat, findFormat, formatsForType, reflectionPromptFor, sizeFor, suggestedGradeFromRubric, wordProgress } from './data/academicSuccessCenter/reportFormats.js';
import { GEORGIA_DAYS_REQUIRED, GEORGIA_LAW_CITATION, GEORGIA_MINUTES_PER_DAY, GEORGIA_REQUIRED_SUBJECTS, GEORGIA_REQUIREMENTS, daysUntil, declarationCoversToday, instructionMinutes, instructionProgress, nextDeclarationDeadline } from './data/admin/georgiaCompliance.js';
import { MISSION_QUARTERS, MISSION_RUBRIC_CRITERIA, MISSION_STATUS_LABELS, draftMissionFeedback, findProposal, missionGrowth, missionScoreTotals, proposalsForQuarter } from './data/admin/missionEvaluations.js';
import { gardenBriefs, getGardenBriefById } from './data/gardening/gardenBriefs.js';
import { gardenBuildTrack, gardenCapstone } from './data/gardening/gardenBuildTrack.js';
import { gardenCalendar, getGardenDayForWeekOf, getNextGardenDay } from './data/gardening/gardenCalendar.js';
import { gardenProjects } from './data/gardening/gardenProjects.js';
import { GUITAR_DAILY_MINUTES, GUITAR_SESSION_SHAPE, getCurrentGuitarSkill, guitarSkillLadder } from './data/guitar/guitarSkillLadder.js';
import { GUITAR_OWN_SLOTS, guitarOwnSongGuidance, guitarPerformanceMoment, guitarStarterSongs } from './data/guitar/guitarSongs.js';
import { guitarTheory } from './data/guitar/guitarTheory.js';
import { getGuitarTool, guitarEducators, guitarFeedbackPlaces } from './data/guitar/guitarTools.js';
import { EXTERNAL_GAMES_LIBRARY } from './data/games/externalGamesLibrary.js';
import { LAUNCH_SCORE_LABELS, PROPELLANT_OPTIONS, STAGING_OPTIONS, TRAJECTORY_EVENT, WEIGHT_BUDGET_CATEGORIES, WEIGHT_BUDGET_TOTAL_POINTS } from './data/games/launchDirectorContent.js';
import { BUDGET_CATEGORIES, BUDGET_TOTAL_POINTS, ECONOMIC_SYSTEMS, GOVERNMENT_TYPES, NATION_SCORE_LABELS, TRADE_EVENT } from './data/games/nationCommandContent.js';
import { QUIZ_PLATFORMS, QUIZ_PLATFORM_IDS } from './data/games/quizPlatforms.js';
import { getDailyLine } from './data/mentor/dailyLines.js';
import { GRAMMAR_COURSES, KHAN_GRAMMAR_UNITS, LEGACY_GRAMMAR_TITLES, generalGrammarUnitByUrl, grammarRowTitle, grammarUnitUrl, khanGrammarUnitByUrl, khanGrammarUnitForUrl } from './data/khan/grammarCourseOrder.js';
import { SCIENCE_CANONICAL_KEYS, SCIENCE_CANONICAL_TITLES, SCIENCE_COURSES, SCIENCE_COURSE_CHALLENGES, scienceCanonicalRow, scienceCourseChallengeRows, scienceCourseForUrl, scienceCoverageByCourse, scienceRowsFor } from './data/khan/scienceSequence.js';
import { allLessons } from './data/lessons/index.js';
import { curatedDemoFor } from './data/pe/exerciseDemoVideos.js';
import { CATEGORY_LABELS, exerciseLibrary } from './data/pe/exerciseLibrary.js';
import { nutritionChallenges, nutritionTopics, recipeLibrary, shoppingListCategories } from './data/pe/nutritionContent.js';
import { HIDDEN_VIDEO, demoLinkFor } from './data/pe/peVideoSource.js';
import { getTodaysWorkout, getWeekNumber } from './data/pe/weeklyWorkoutPlan.js';
import { aerospaceProjects } from './data/aerospace/aerospaceProjects.js';
import { roboticsProjects } from './data/robotics/roboticsProjects.js';
import { scienceExperiments } from './data/science/scienceExperiments.js';
import { technologyProjects } from './data/technology/technologyProjects.js';
import { HQ_CREW } from './data/hqCrew.js';
import { journalFor, printoutFor } from './data/printouts.js';
import { AVATAR_GEAR, COIN_CATALOG, HQ_ITEMS, MISSION_EQUIPMENT, SEEDED_REWARD_LADDER_MAP, affordable, catalogRewardRows, costForCosmetic } from './data/rewardCatalog.js';
import { ACTIVE_SUBJECTS, KHAN_TAUGHT_SUBJECTS, LESSON_TRACK_SUBJECTS, PARTICIPATION_SUBJECTS, SUBJECT_LABELS, canonicalSubject, isKhanTaughtSubject, strandsForSubject, subjectCardLabel } from './subjects.js';
import { defaultSchedule } from './data/schedule/defaultSchedule.js';
import { holidaysInSpan, isHoliday, isSchoolDay } from './data/schedule/schoolHolidays.js';
import { WEEK_PATTERN, dayPattern, patternSubjects, subjectsForDay } from './data/schedule/weekPattern.js';
import { dailyDrills } from './data/writing/dailyDrills.js';
import { requirementsFor } from './data/writing/drillRequirements.js';
import { lessonForPrompt } from './data/writing/promptLessons.js';
import { spellingWordPool } from './data/writing/spellingWordPool.js';
import { EDCLUB_PORTAL_URL, ERGONOMICS_CHECKLIST, typingLessons } from './data/writing/typingLessons.js';
import { vocabularyWordPool } from './data/writing/vocabularyWordPool.js';
import { SCHOOL_YEAR_START, getSchoolWeekNumber, getThisWeeksScheduledIds, weeklyWritingSchedule } from './data/writing/weeklySchedule.js';
import { writingPrompts } from './data/writing/writingPrompts.js';

export const academicCenter = { ACADEMIC_ASSIGNMENT_TYPES, ACADEMIC_BOOK_TYPES, ACADEMIC_SUBJECT_ORDER, ACADEMIC_SUCCESS_CENTER_QUARTER_ORDER, BLACK_EXCELLENCE_KNOWN_GAPS, BOOK_RANGE_LABELS, EXCLUDED_RANGES, RUBRIC_LEVELS, activeMilestone, assignmentCandidatesForSlot, availableDueDates, blackAmericanAuthorsForSubject, blackExcellenceBooksForSubject, bookRationale, bookRecommendations, candidatesForBook, criteriaForFormat, findFormat, formatsForType, hasMilestones, leadStatus, milestoneProgress, milestonesFor, nextAssignmentRecommendation, nextRecommendationForBook, quarterlyAcademicPlaceholders, rationaleFor, reflectionPromptFor, resolveSuggestedDueDate, sizeFor, startByFor, subjectBookPlaceholders, suggestedGradeFromRubric, wordProgress };

export const compliance = { GEORGIA_DAYS_REQUIRED, GEORGIA_LAW_CITATION, GEORGIA_MINUTES_PER_DAY, GEORGIA_REQUIRED_SUBJECTS, GEORGIA_REQUIREMENTS, MISSION_QUARTERS, MISSION_RUBRIC_CRITERIA, MISSION_STATUS_LABELS, daysUntil, declarationCoversToday, draftMissionFeedback, findProposal, instructionMinutes, instructionProgress, missionGrowth, missionScoreTotals, nextDeclarationDeadline, proposalsForQuarter };

export const electives = { GUITAR_DAILY_MINUTES, GUITAR_OWN_SLOTS, GUITAR_SESSION_SHAPE, gardenBriefs, gardenBuildTrack, gardenCalendar, gardenCapstone, gardenProjects, getCurrentGuitarSkill, getGardenBriefById, getGardenDayForWeekOf, getGuitarTool, getNextGardenDay, guitarEducators, guitarFeedbackPlaces, guitarOwnSongGuidance, guitarPerformanceMoment, guitarSkillLadder, guitarStarterSongs, guitarTheory };

export const games = { BUDGET_CATEGORIES, BUDGET_TOTAL_POINTS, ECONOMIC_SYSTEMS, EXTERNAL_GAMES_LIBRARY, GOVERNMENT_TYPES, LAUNCH_SCORE_LABELS, NATION_SCORE_LABELS, PROPELLANT_OPTIONS, QUIZ_PLATFORMS, QUIZ_PLATFORM_IDS, STAGING_OPTIONS, TRADE_EVENT, TRAJECTORY_EVENT, WEIGHT_BUDGET_CATEGORIES, WEIGHT_BUDGET_TOTAL_POINTS };

export const guide = { getDailyLine };

export const khanSequences = { GRAMMAR_COURSES, KHAN_GRAMMAR_UNITS, LEGACY_GRAMMAR_TITLES, SCIENCE_CANONICAL_KEYS, SCIENCE_CANONICAL_TITLES, SCIENCE_COURSES, SCIENCE_COURSE_CHALLENGES, generalGrammarUnitByUrl, grammarRowTitle, grammarUnitUrl, khanGrammarUnitByUrl, khanGrammarUnitForUrl, scienceCanonicalRow, scienceCourseChallengeRows, scienceCourseForUrl, scienceCoverageByCourse, scienceRowsFor };

export const lessons = { allLessons };

export const pe = { CATEGORY_LABELS, HIDDEN_VIDEO, curatedDemoFor, demoLinkFor, exerciseLibrary, getTodaysWorkout, getWeekNumber, nutritionChallenges, nutritionTopics, recipeLibrary, shoppingListCategories };

export const projects = { aerospaceProjects, roboticsProjects, scienceExperiments, technologyProjects };

export const rewards = { AVATAR_GEAR, COIN_CATALOG, HQ_CREW, HQ_ITEMS, MISSION_EQUIPMENT, SEEDED_REWARD_LADDER_MAP, affordable, catalogRewardRows, costForCosmetic, journalFor, printoutFor };

export const subjects = { ACTIVE_SUBJECTS, KHAN_TAUGHT_SUBJECTS, LESSON_TRACK_SUBJECTS, PARTICIPATION_SUBJECTS, SUBJECT_LABELS, canonicalSubject, isKhanTaughtSubject, strandsForSubject, subjectCardLabel };

export const timetable = { WEEK_PATTERN, dayPattern, defaultSchedule, holidaysInSpan, isHoliday, isSchoolDay, patternSubjects, subjectsForDay };

export const writing = { EDCLUB_PORTAL_URL, ERGONOMICS_CHECKLIST, SCHOOL_YEAR_START, dailyDrills, getSchoolWeekNumber, getThisWeeksScheduledIds, lessonForPrompt, requirementsFor, spellingWordPool, typingLessons, vocabularyWordPool, weeklyWritingSchedule, writingPrompts };

/**
 * This Academy's palette and print rules.
 *
 * A function rather than a static import so the stylesheet travels in this
 * Academy's chunk and loads when this Academy does. A static import here
 * would put every Academy's theme in every learner's download, which is the
 * thing the folder split exists to prevent.
 */
export const theme = { load: () => import('./academy.css') };
